version: '2'
services:
  users-app:
    image: users
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://users-mariadb:3306/users?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  users-mariadb:
    extends:
      file: mariadb.yml
      service: users-mariadb
