export const enum Religiao {
  CATOLICO = 'CATOLICO',

  PROTESTANTE = 'PROTESTANTE',

  EVANGELICO = 'EVANGELICO',

  ESPIRITA = 'ESPIRITA',

  AFRO_BRASILEIRA = 'AFRO_BRASILEIRA',

  BUDISMO = 'BUDISMO',

  JUDAICA = 'JUDAICA',

  OUTRA = 'OUTRA',
}
